export const products = [
  {
    id: 1,
    img: "https://i.ibb.co/nndT2gm/Screenshot-225.png",
    title: "Food Application",
    link: "https://react-food-app-project.netlify.app",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae natu perspiciatis voluptatibus impedit, numquam labore, illo praesentium sint ipsa ad, velit recusandae. Hic temporibus, blanditiis quis reiciendis praesentium nisi quia.",
    code: "https://github.com/mohammed-summers/react-food-app",
  },
  {
    id: 2,
    img: "https://i.ibb.co/PFxjm0y/Screenshot-230.png",
    title: "CocktailDB",
    link: "https://react-cocktailbd.netlify.app",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae natu perspiciatis voluptatibus impedit, numquam labore, illo praesentium sint ipsa ad, velit recusandae. Hic temporibus, blanditiis quis reiciendis praesentium nisi quia.",
    code: "https://github.com/mohammed-summers/react-cocktaildb",
  },
  {
    id: 3,
    img: "https://i.ibb.co/VLkSW2V/Screenshot-232.png",
    title: "Github User Finder",
    link: "https://ms-github-user-finder.netlify.app",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae natu perspiciatis voluptatibus impedit, numquam labore, illo praesentium sint ipsa ad, velit recusandae. Hic temporibus, blanditiis quis reiciendis praesentium nisi quia.",
    code: "https://github.com/mohammed-summers/github-user-finder",
  },
  {
    id: 4,
    img: "https://i.ibb.co/VLkSW2V/Screenshot-232.png",
    title: "Github User Finder",
    ink: "https://ms-github-user-finder.netlify.app",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae natu perspiciatis voluptatibus impedit, numquam labore, illo praesentium sint ipsa ad, velit recusandae. Hic temporibus, blanditiis quis reiciendis praesentium nisi quia.",
    code: "https://github.com/mohammed-summers/github-user-finder",
  },
  {
    id: 5,
    img: "https://i.ibb.co/VLkSW2V/Screenshot-232.png",
    title: "Github User Finder",
    ink: "https://ms-github-user-finder.netlify.app",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae natu perspiciatis voluptatibus impedit, numquam labore, illo praesentium sint ipsa ad, velit recusandae. Hic temporibus, blanditiis quis reiciendis praesentium nisi quia.",
    code: "https://github.com/mohammed-summers/github-user-finder",
  },
];
